# crypto-miner-managertask-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: crypto-miner-manager

outputs:
- name: coverage-results

run:
  path: ./crypto-miner-manager/ci/scripts/unit-tests.sh
  # args: [-debug]
