# catch-microservice task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: catch-microservice

outputs:
- name: catch-microservice-updated

run:
  path: ./catch-microservice/ci/scripts/readme-github-pages.sh
  # args: [-debug]
