# crypto-miner-manager task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19

inputs:
- name: crypto-miner-manager

outputs:
- name: crypto-miner-manager-updated

run:
  path: ./crypto-miner-manager/ci/scripts/readme-github-pages.sh
  # args: [-debug]
