# catch-microservice task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: catch-microservice

run:
  path: ./catch-microservice/ci/scripts/deploy.sh
  # args: [-debug]
