# crypto-miner-manager task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jeffdecola/crypto-miner-manager
    tag: latest

inputs:
- name: crypto-miner-manager

run:
  path: ./crypto-miner-manager/ci/scripts/deploy.sh
  # args: [-debug]
