# crypto-miner-manager task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: crypto-miner-manager

outputs:
- name: dist

run:

  path: ./crypto-miner-manager/ci/scripts/build-push.sh
  # args: [-debug]
