# crypto-miner-manager pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-deploy
#**********************************************
  plan:
    # GET REPO FROM GITHUB
    - get: crypto-miner-manager
      trigger: true
    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE 
    - task: task-deploy
      file: crypto-miner-manager/ci/tasks/task-deploy.yml
      params:
        DOCKER_HOST_SSH_PRIVATE_KEY: {{docker_host_ssh_private_key}}
        DOCKER_HOST_PORT: '22'
        DOCKER_HOST_USER: 'jeffry'
        DOCKER_HOST_IP: '192.168.20.122'

#------------------------------------------------------------------------------------------
resources:

- name: crypto-miner-manager
  type: git
  icon: github
  source:
    #uri: https://github.com/jeffdecola/crypto-miner-manager
    uri: git@github.com:jeffdecola/crypto-miner-manager.git
    branch: master
    private_key: ((git_private_key))
