# crypto-miner-manager pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-deploy
#**********************************************
  plan:
    - get: resource-deploy-from-dockerhub
      trigger: true
    - task: task-deploy
      file: crypto-miner-manager/ci/tasks/task-deploy.yml

#------------------------------------------------------------------------------------------
resources:

- name: resource-deploy-from-dockerhub
  type: docker-image
  icon: docker
  source:
    repository: jeffdecola/crypto-miner-manager
    tag: latest
