# crypto-miner-manager pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-deploy
#**********************************************
  plan:
    - get: crypto-miner-manager
      trigger: true
    - task: task-deploy
      file: crypto-miner-manager/ci/tasks/task-deploy.yml

#------------------------------------------------------------------------------------------
resources:

- name: crypto-miner-manager
  type: git
  icon: github
  source:
    #uri: https://github.com/jeffdecola/crypto-miner-manager
    uri: git@github.com:jeffdecola/crypto-miner-manager.git
    branch: master
    private_key: ((git_private_key))

- name: resource-deploy-from-dockerhub
  type: docker-image
  icon: docker
  source:
    repository: jeffdecola/crypto-miner-manager
    tag: latest
